### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by DonnyBahama** [ChristopherRogers1991/mycroft-irsend#3]
Any chance you could do a write-up on the hardware it takes to make this happen? Or even just link to a page where it's documented?

**Comment by ChristopherRogers1991** [comment]
I can't do a full write up now, but quickly:

https://www.iguanaworks.net/products/usb-ir-transceiver/ is what I use. Their [wiki](https://www.iguanaworks.net/wiki/usbir:gettingstarted) has instructions for making it work. Once you've got it set up, it works well, but it is a little involved to get it set up. You may be able to find another transmitter with more out-of-the-box support. Just make sure whatever you get works with LIRC.

As a note, the specific advantage to getting a transceiver is that you can use it to read signals from remotes you have, and generate the files LIRC needs to talk to your specific devices. E.g. you can point your television remote at the transceiver, peed all the buttons, and generate a file that can be used to emulate that remote. You'll use [irrecord](http://www.lirc.org/html/irrecord.html) for that (which should come with your LIRC package).

Also, fwiw, there are guides about setting this up LIRC with a raspberry pi specifically, e.g. https://www.hackster.io/austin-stanton/creating-a-raspberry-pi-universal-remote-with-lirc-2fd581.

Worth noting is that the LIRC service does not need to run on the same host as Mycroft; LIRC runs as server and can accept commands over the network (you'll need irsend on both machines, but the LIRC server should only need to be running on the host with the transmitter).

**Comment by DonnyBahama** [comment]
OK. Thanks for that! I have an old USB-UIRT around somewhere. It works well with Lirc but I don’t know if there’s still any support for it. I also have IR emitters and receivers and (probably) all the components I need to wire it up using GPIO pins. I was hoping that’s what you had done so you could provide a step-by-step but I have several articles bookmarked/Evernoted for doing so, so hopefully I’ll manage to get this going one way or another! Thanks again for the response - and the really cool skill!

**Comment by ChristopherRogers1991** [comment]
Good luck! For what it's worth, if you haven't seen it already, I'd highly recommend you pair this skill with my routine skill: https://github.com/ChristopherRogers1991/mycroft_routine_skill.

**Comment by DonnyBahama** [comment]
Yeah, your routine skill is AWESOME! That’s what led me to this skill. Quick question- do you know if routines created using your skill be triggered by Home Assistant?

**Comment by ChristopherRogers1991** [comment]
I have no experience with home assistant. When that in mind:

The routine skill works by sending arbitrary text to the message bus. Once you've created a routine, it's trigger-able in the same way - you just send the name of the routine to Mycroft's message bus (as a note, this means you can create routines that trigger other routines). So if home assistant (or any other tool) can send text to the message bus, it can trigger the routines (or any other Mycroft skill).
